# Generated by Django 5.0.6 on 2024-07-20 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=25)),
                ('strength', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('intellegence', models.IntegerField()),
                ('charizma', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('acrobatics', models.BooleanField()),
                ('analysis', models.BooleanField()),
                ('athletics', models.BooleanField()),
                ('perception', models.BooleanField()),
                ('survival', models.BooleanField()),
                ('performance', models.BooleanField()),
                ('intimidation', models.BooleanField()),
                ('history', models.BooleanField()),
                ('sleight_hand', models.BooleanField()),
                ('magic', models.BooleanField()),
                ('medicine', models.BooleanField()),
                ('deception', models.BooleanField()),
                ('nature', models.BooleanField()),
                ('insight', models.BooleanField()),
                ('religic', models.BooleanField()),
                ('stealth', models.BooleanField()),
                ('conviction', models.BooleanField()),
                ('caring', models.BooleanField()),
                ('max_health', models.IntegerField()),
                ('items', models.TextField(default='Ваше Снаряжение')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.myhero')),
            ],
        ),
    ]
