# Generated by Django 5.0.6 on 2024-07-12 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=25)),
                ('strength', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('intellegence', models.IntegerField()),
                ('charizma', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('acrobatics', models.BooleanField()),
                ('analysis', models.BooleanField()),
                ('athletics', models.BooleanField()),
                ('perception', models.BooleanField()),
                ('survival', models.BooleanField()),
                ('performance', models.BooleanField()),
                ('history', models.BooleanField()),
                ('sleight_hand', models.BooleanField()),
                ('magic', models.BooleanField()),
                ('medicine', models.BooleanField()),
                ('deception', models.BooleanField()),
                ('nature', models.BooleanField()),
                ('insight', models.BooleanField()),
                ('religic', models.BooleanField()),
                ('stealth', models.BooleanField()),
                ('conviction', models.BooleanField()),
                ('caring', models.BooleanField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
